- type: job
  id: Vicar
  name: job-name-vicar
  description: job-description-vicar
  playTimeTracker: JobVicar
  requirements:
  - !type:DepartmentTimeRequirement
    department: Ecclesia
    time: 43200 # 12 hours
  weight: 10
  startingGear: VicarGear
  guides: [ Ecclesia ]
  icon: "JobIconChiefMedicalOfficer"
  supervisors: job-supervisors-nobles
  canBeAntag: false
  accessGroups:
  - VicarAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: SurgerySpeedModifier
      SpeedModifier: 2.5

- type: startingGear
  id: VicarGear
  equipment:
    id: CMOPDA
    ears: ClothingHeadsetCMO
  storage:
    back:
    - Flash

- type: accessGroup
  id: VicarAccess
  tags:
  - Maintenance
  - External
  - Command
  - Medical

- type: playTimeTracker
  id: JobVicar

- type: entity
  id: SpawnPointVicar
  parent: SpawnPointChiefMedicalOfficer
  name: Vicar
  components:
  - type: SpawnPoint
    job_id: Vicar

- type: roleLoadout
  id: JobVicar
  groups:
  - VicarHead
  - VicarNeck
  - VicarJumpsuit
  - EcclesiaGloves
  - EcclesiaBackpack
  - VicarOuterClothing
  - EcclesiaShoes
  - GeneralFace
  - GeneralGlasses
  - GeneralBelt
#  - EcclesiaEars # Commented this out because it's filled by the StartingGear component.
  - ContractorBoxSurvival
#  - EcclesiaPDA # Commented this out because it's filled by the StartingGear component.
  - GeneralWallet
  - GeneralCartridge
  - GeneralImplanter
  - GeneralEncryptionKey
  - GeneralFun
  - GeneralTrinkets
  - GeneralBureaucracy
  - NFSpeciesSpecific
  - GeneralFirearm
  - GeneralMag
