- type: job
  id: Helmsman
  name: job-name-helmsman
  description: job-description-helmsman
  playTimeTracker: JobHelmsman
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 21600 # 6 hours
  whitelisted: true
  startingGear: HelmsmanGear
  alwaysUseSpawner: true
  icon: "JobIconCaptain"
  requireAdminNotify: true
  supervisors: job-supervisors-shipbaron
  weight: 170
  displayWeight: 60
  canBeAntag: false
  guides: [ BasicLore ]
  accessGroups:
  - AllAccessSR
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: HelmsmanGear
  equipment:
    pocket1: WeaponDisabler
  storage:
    back:
    - Flash
    - RubberStampSr
    - DoorRemoteCommand
    - EncryptionKeyCentCom
    - EncryptionKeyStationMasterSR #Mono start
    - EncryptionKeyDiplomacy
    - ShipVoucherFrontierGuard
   #- EncryptionKeyStationMaster # Mono end

- type: playTimeTracker
  id: JobHelmsman

- type: entity
  id: SpawnPointHelmsman
  parent: SpawnPointHeadOfPersonnel
  name: helmsman
  components:
  - type: SpawnPoint
    job_id: Helmsman

- type: roleLoadout
  id: JobHelmsman
  groups:
  #  - StationRepHead
  #  - StationRepNeck
  #  - StationRepJumpsuit
  - StationRepGloves
  - StationRepBackpack
  - StationRepOuterClothing
  #  - GeneralShoes
  #  - GeneralFace
  #  - GeneralGlasses
  #  - GeneralBelt
  - MonoSecurityGuardHud
  - StationRepEars
  - MonoSecurityGuardShoes
  - HeadofSecurityHead
  - HeadofSecurityJumpsuit
  - HeadofSecurityNeck
  - ColonialLiaisonFirearm # Mono
  - GeneralBoxSurvival
  - StationRepPDA
  - GeneralWallet
  - GeneralCartridge
  - GeneralImplanter
  # - GeneralFun # Mono - no fun allowed
  - StationRepTrinkets
  - GeneralBureaucracy
  - NFSpeciesSpecific
