- type: job
  id: Helmsman
  name: job-name-helmsman
  description: job-description-helmsman
  playTimeTracker: JobHelmsman
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 21600 # 6 hours
  whitelisted: true
  startingGear: HelmsmanGear
  alwaysUseSpawner: true
  icon: "JobIconCaptain"
  requireAdminNotify: true
  supervisors: job-supervisors-shipbaron
  weight: 170
  displayWeight: 60
  canBeAntag: false
  guides: [ BasicLore ]
  accessGroups:
  - AllAccessSR
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: HelmsmanGear
  equipment:
    pocket1: WeaponDisabler
    ears: ClothingHeadsetCommand
  storage:
    back:
    - Flash

- type: playTimeTracker
  id: JobHelmsman

- type: entity
  id: SpawnPointHelmsman
  parent: SpawnPointHeadOfPersonnel
  name: helmsman
  components:
  - type: SpawnPoint
    job_id: Helmsman

- type: roleLoadout
  id: JobHelmsman
  groups:
  - NobleJumpsuit
  - NobleBackpack
  - NobleGloves
  - NobleOuterClothing
  - NobleFace
  - NobleGlasses
#  - NobleEars # Commented this out because it's filled by the StartingGear component.
  - GeneralEncryptionKey
  - NobleShoes
  - NobleHead
  - NobleNeck
  - GeneralBoxSurvival
  - NoblePDA
  - GeneralWallet
  - GeneralCartridge
  - GeneralImplanter
  - GeneralFun
  - GeneralUtility
  - GeneralTrinkets
  - GeneralBureaucracy
  - NFSpeciesSpecific
