- type: job
  id: Hand
  name: job-name-hand
  description: job-description-hand
  playTimeTracker: JobHand
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 21600 # 6 hours
  whitelisted: true
  startingGear: HandGear
  alwaysUseSpawner: true
  icon: "JobIconNanotrasen"
  requireAdminNotify: true
  supervisors: job-supervisors-shipbaron
  weight: 170
  displayWeight: 60
  canBeAntag: false
  guides: [ BasicLore ]
  accessGroups:
  - AllAccessSR
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: HandGear
  equipment:
    pocket1: WeaponDisabler
    ears: ClothingHeadsetCommand
  storage:
    back:
    - Flash

- type: playTimeTracker
  id: JobHand

- type: entity
  id: SpawnPointHand
  parent: SpawnPointHeadOfPersonnel
  name: hand
  components:
  - type: SpawnPoint
    job_id: Hand

- type: roleLoadout
  id: JobHand
  groups:
  - NobleJumpsuit
  - NobleBackpack
  - NobleGloves
  - NobleOuterClothing
  - NobleFace
  - NobleGlasses
  #  - NobleEars # Commented this out because it's filled by the StartingGear component.
  - GeneralEncryptionKey
  - NobleShoes
  - NobleHead
  - NobleNeck
  - GeneralBoxSurvival
  - NoblePDA
  - GeneralWallet
  - GeneralCartridge
  - GeneralImplanter
  - GeneralFun
  - GeneralUtility
  - GeneralTrinkets
  - GeneralBureaucracy
  - NFSpeciesSpecific
