- type: job
  id: Heir
  name: job-name-heir
  description: job-description-heir
  playTimeTracker: JobHeir
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 21600 # 6 hours
  whitelisted: true
  startingGear: HeirGear
  alwaysUseSpawner: true
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-shipbaron
  weight: 170
  displayWeight: 60
  canBeAntag: false
  guides: [ BasicLore ]
  accessGroups:
  - AllAccessSR
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: HeirGear
  equipment:
    pocket1: WeaponDisabler
    ears: ClothingHeadsetCommand
  storage:
    back:
    - Flash

- type: playTimeTracker
  id: JobHeir

- type: entity
  id: SpawnPointHeir
  parent: SpawnPointHeadOfPersonnel
  name: heir
  components:
  - type: SpawnPoint
    job_id: Heir

- type: roleLoadout
  id: JobHeir
  groups:
  - NobleJumpsuit
  - NobleBackpack
  - NobleGloves
  - NobleOuterClothing
  - NobleFace
  - NobleGlasses
  #  - NobleEars # Commented this out because it's filled by the StartingGear component.
  - GeneralEncryptionKey
  - NobleShoes
  - NobleHead
  - NobleNeck
  - GeneralBoxSurvival
  - NoblePDA
  - GeneralWallet
  - GeneralCartridge
  - GeneralImplanter
  - GeneralFun
  - GeneralUtility
  - GeneralTrinkets
  - GeneralBureaucracy
  - NFSpeciesSpecific
