- type: job
  id: Heir
  name: job-name-heir
  description: job-description-heir
  playTimeTracker: JobHeir
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 21600 # 6 hours
  whitelisted: true
  startingGear: HeirGear
  alwaysUseSpawner: true
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-shipbaron
  weight: 170
  displayWeight: 60
  canBeAntag: false
  guides: [ BasicLore ]
  accessGroups:
  - AllAccessSR
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: HeirGear
  equipment:
    pocket1: WeaponDisabler
  storage:
    back:
    - Flash
    - RubberStampSr
    - DoorRemoteCommand
    - EncryptionKeyCentCom
    - EncryptionKeyStationMasterSR #Mono start
    - EncryptionKeyDiplomacy
    - ShipVoucherFrontierGuard
   #- EncryptionKeyStationMaster # Mono end

- type: playTimeTracker
  id: JobHeir

- type: entity
  id: SpawnPointHeir
  parent: SpawnPointHeadOfPersonnel
  name: heir
  components:
  - type: SpawnPoint
    job_id: Heir

- type: roleLoadout
  id: JobHeir
  groups:
  #  - StationRepHead
  #  - StationRepNeck
  #  - StationRepJumpsuit
  - StationRepGloves
  - StationRepBackpack
  - StationRepOuterClothing
  #  - GeneralShoes
  #  - GeneralFace
  #  - GeneralGlasses
  #  - GeneralBelt
  - MonoSecurityGuardHud
  - StationRepEars
  - MonoSecurityGuardShoes
  - HeadofSecurityHead
  - HeadofSecurityJumpsuit
  - HeadofSecurityNeck
  - ColonialLiaisonFirearm # Mono
  - GeneralBoxSurvival
  - StationRepPDA
  - GeneralWallet
  - GeneralCartridge
  - GeneralImplanter
  # - GeneralFun # Mono - no fun allowed
  - StationRepTrinkets
  - GeneralBureaucracy
  - NFSpeciesSpecific
