- type: job
  id: Provost
  name: job-name-provost
  description: job-description-provost
  playTimeTracker: JobProvost
  requirements:
  - !type:DepartmentTimeRequirement
    department: Vistula
    time: 43200 # 12 hours
  weight: 10
  guides: [ VistulaInstitute ]
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-nobles
  canBeAntag: false
  accessGroups:
  - ProvostAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: ProvostGear
  equipment:
    id: SciencePDA
    ears: ClothingHeadsetScience

- type: accessGroup
  id: ProvostAccess
  tags:
  - Maintenance
  - External
  - Command
  - Research

- type: playTimeTracker
  id: JobProvost

- type: entity
  id: SpawnPointProvost
  parent: SpawnPointResearchDirector
  name: Provost
  components:
  - type: SpawnPoint
    job_id: Provost

- type: roleLoadout
  id: JobProvost
  groups:
  - VistulaHead
  - VistulaNeck
  - ProvostJumpsuit
  - VistulaGloves
  - VistulaBackpack
  - GeneralOuterClothing
  - VistulaShoes
  - GeneralFace
  - GeneralGlasses
  - GeneralBelt
#  - VistulaEars # Commented this out because it's filled by the StartingGear component.
  - GeneralBoxSurvival
#  - VistulaPDA # Commented this out because it's filled by the StartingGear component.
  - GeneralWallet
  - GeneralCartridge
  - GeneralImplanter
  - GeneralEncryptionKey
  - GeneralFun
  - GeneralTrinkets
  - GeneralBureaucracy
  - NFSpeciesSpecific
  - GeneralFirearm
  - GeneralMag
