- type: job
  id: Researcher
  name: job-name-researcher
  description: job-description-researcher
  playTimeTracker: JobResearcher
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1 hr
  guides: [ VistulaInstitute ]
  icon: "JobIconScientist"
  supervisors: job-supervisors-provost
  accessGroups:
  - VistulaAccess

- type: accessGroup
  id: VistulaAccess
  tags:
  - Maintenance
  - External
  - Research

- type: playTimeTracker
  id: JobResearcher

- type: entity
  id: SpawnPointResearcher
  parent: SpawnPointScientist
  name: Researcher
  components:
  - type: SpawnPoint
    job_id: Researcher

- type: roleLoadout
  id: JobResearcher
  groups:
  - GeneralHead
  - GeneralNeck
  - MdMedicJumpsuit
  - MdMedicGloves
  - MdMedicBackpack
  - GeneralOuterClothing
  - GeneralShoes
  - GeneralFace
  - GeneralGlasses
  - GeneralBelt
  - MdMedicEars
  - GeneralBoxSurvival
  - MdMedicPDA
  - GeneralWallet
  - GeneralCartridge
  - GeneralImplanter
  - GeneralEncryptionKey
  - GeneralFun
  - GeneralTrinkets
  - GeneralBureaucracy
  - NFSpeciesSpecific
  - GeneralFirearm
  - GeneralMag
