- type: job
  id: Researcher
  name: job-name-researcher
  description: job-description-researcher
  playTimeTracker: JobResearcher
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1 hr
  guides: [ VistulaInstitute ]
  icon: "JobIconScientist"
  supervisors: job-supervisors-provost
  accessGroups:
  - VistulaAccess

- type: startingGear
  id: ResearcherGear
  equipment:
    id: SciencePDA
    ears: ClothingHeadsetScience

- type: accessGroup
  id: VistulaAccess
  tags:
  - Maintenance
  - External
  - Research

- type: playTimeTracker
  id: JobResearcher

- type: entity
  id: SpawnPointResearcher
  parent: SpawnPointScientist
  name: Researcher
  components:
  - type: SpawnPoint
    job_id: Researcher

- type: roleLoadout
  id: JobResearcher
  groups:
  - VistulaHead
  - VistulaNeck
  - VistulaJumpsuit
  - VistulaGloves
  - VistulaBackpack
  - GeneralOuterClothing
  - GeneralShoes
  - GeneralFace
  - GeneralGlasses
  - GeneralBelt
#  - VistulaEars # Commented this out because it's filled by the StartingGear component.
  - GeneralBoxSurvival
#  - VistulaPDA # Commented this out because it's filled by the StartingGear component.
  - GeneralWallet
  - GeneralCartridge
  - GeneralImplanter
  - GeneralEncryptionKey
  - GeneralFun
  - GeneralTrinkets
  - GeneralBureaucracy
  - NFSpeciesSpecific
  - GeneralFirearm
  - GeneralMag
