- type: job
  id: Clerk
  name: job-name-clerk
  description: job-description-clerk
  playTimeTracker: JobClerk
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-steward
  displayWeight: 40
  guides: [ BasicLore ]
  accessGroups:
  - GeneralAccess
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: playTimeTracker
  id: JobClerk

- type: entity
  id: SpawnPointClerk
  parent: SpawnPointCargoTechnician
  name: clerk
  components:
  - type: SpawnPoint
    job_id: Clerk

- type: roleLoadout
  id: JobClerk
  groups:
  - GeneralHead
  - GeneralNeck
  - GeneralJumpsuit
  - GeneralGloves
  - GeneralBackpack
  - GeneralOuterClothing
  - GeneralShoes
  - GeneralFace
  - GeneralGlasses
  - GeneralBelt
  - GeneralEars
  - GeneralEncryptionKey
  - GeneralBoxSurvival
  - GeneralPDA
  - GeneralWallet
  - GeneralCartridge
  - GeneralImplanter
  - GeneralUtility
  - GeneralFun
  - GeneralTrinkets
  - GeneralBureaucracy
  - NFSpeciesSpecific
  - GeneralFirearm
  - GeneralMag
