- type: job
  id: Clerk
  name: job-name-clerk
  description: job-description-clerk
  playTimeTracker: JobClerk
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-steward
  displayWeight: 40
  guides: [ BasicLore ]
  accessGroups:
  - GeneralAccess
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: playTimeTracker
  id: JobClerk

- type: entity
  id: SpawnPointClerk
  parent: SpawnPointCargoTechnician
  name: clerk
  components:
  - type: SpawnPoint
    job_id: Clerk

- type: roleLoadout
  id: JobClerk
  groups:
  - ContractorHead
  - ContractorNeck
  - ContractorJumpsuit
  - ContractorGloves
  - ContractorBackpack
  - ContractorOuterClothing
  - ContractorShoes
  - ContractorFace
  - ContractorGlasses
  - ContractorBelt
  - ContractorEars
  - ContractorEncryptionKey
  - ContractorBoxSurvival
  - ContractorPDA
  - ContractorWallet
  - ContractorCartridge
  - ContractorImplanter
  - ContractorUtility
  - ContractorFun
  - ContractorTrinkets
  - ContractorBureaucracy
  - NFSpeciesSpecific
  - ContractorFirearm # Mono
  - ContractorMag # Mono
