- type: job
  id: FirstEngineer
  name: job-name-first-engineer
  description: job-description-first-engineer
  playTimeTracker: JobFirstEngineer
  icon: "JobIconStationEngineer"
  supervisors: job-supervisors-steward
  displayWeight: 40
  guides: [ BasicLore ]
  accessGroups:
  - GeneralAccess
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: playTimeTracker
  id: JobFirstEngineer

- type: entity
  id: SpawnPointFirstEngineer
  parent: SpawnPointStationEngineer
  name: first-engineer
  components:
  - type: SpawnPoint
    job_id: FirstEngineer

- type: roleLoadout
  id: JobFirstEngineer
  groups:
  - GeneralHead
  - GeneralNeck
  - GeneralJumpsuit
  - GeneralGloves
  - GeneralBackpack
  - GeneralOuterClothing
  - GeneralShoes
  - GeneralFace
  - GeneralGlasses
  - GeneralBelt
  - GeneralEars
  - GeneralEncryptionKey
  - GeneralBoxSurvival
  - GeneralPDA
  - GeneralWallet
  - GeneralCartridge
  - GeneralImplanter
  - GeneralUtility
  - GeneralFun
  - GeneralTrinkets
  - GeneralBureaucracy
  - NFSpeciesSpecific
  - GeneralFirearm
  - GeneralMag
