- type: job
  id: Rating
  name: job-name-rating
  description: job-description-rating
  playTimeTracker: JobRating
  icon: "JobIconContractor"
  supervisors: job-supervisors-steward
  displayWeight: 40
  guides: [ BasicLore ]
  accessGroups:
  - GeneralAccess
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: playTimeTracker
  id: JobRating

- type: entity
  id: SpawnPointRating
  parent: SpawnPointPassenger
  name: rating
  components:
  - type: SpawnPoint
    job_id: Rating

- type: roleLoadout
  id: JobRating
  groups:
  - GeneralHead
  - GeneralNeck
  - GeneralJumpsuit
  - GeneralGloves
  - GeneralBackpack
  - GeneralOuterClothing
  - GeneralShoes
  - GeneralFace
  - GeneralGlasses
  - GeneralBelt
  - GeneralEars
  - GeneralEncryptionKey
  - GeneralBoxSurvival
  - GeneralPDA
  - GeneralWallet
  - GeneralCartridge
  - GeneralImplanter
  - GeneralUtility
  - GeneralFun
  - GeneralTrinkets
  - GeneralBureaucracy
  - NFSpeciesSpecific
  - GeneralFirearm
  - GeneralMag
