- type: job
  id: Vagabond
  name: job-name-vagabond
  description: job-description-vagabond
  playTimeTracker: JobVagabond
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1 hrs
  icon: "JobIconPassenger"
  supervisors: job-supervisors-noone
  displayWeight: 41
  guides: [ BasicLore ]
  accessGroups:
  - VagabondAccess
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: playTimeTracker
  id: JobVagabond

- type: entity
  id: SpawnPointVagabond
  parent: SpawnPointPassenger
  name: vagabond
  components:
  - type: SpawnPoint
    job_id: Vagabond

- type: roleLoadout
  id: JobVagabond
  groups:
  - GeneralHead
  - GeneralNeck
  - GeneralJumpsuit
  - GeneralGloves
  - GeneralBackpack
  - GeneralOuterClothing
  - GeneralShoes
  - GeneralFace
  - GeneralGlasses
  - GeneralBelt
  - GeneralEars
  - GeneralEncryptionKey
  - GeneralBoxSurvival
  - GeneralPDA
  - GeneralWallet
  - GeneralCartridge
  - GeneralImplanter
  - GeneralUtility
  - GeneralFun
  - GeneralTrinkets
  - GeneralBureaucracy
  - NFSpeciesSpecific
  - GeneralFirearm
  - GeneralMag

- type: accessGroup
  id: VagabondAccess
  tags:
  - Maintenance
