- type: job
  id: Marshal
  name: job-name-marshal
  description: job-description-marshal
  playTimeTracker: JobMarshal
  requirements:
    - !type:DepartmentTimeRequirement
      department: Knights
      time: 43200 # 12 hours
  whitelisted: true
  startingGear: MarshalGear
  alwaysUseSpawner: true
  icon: "JobIconHeadOfSecurity"
  requireAdminNotify: true
  supervisors: job-supervisors-shipbaron
  weight: 180
  displayWeight: 70
  canBeAntag: false
  guides: [ BasicLore ]
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: MarshalGear
  equipment:
    pocket1: WeaponEnergyGunMultiphase # DeltaV gun
    pocket2: EnergySwordNfsd
  storage:
    back:
    - Multitool
    - DoorRemoteNfsd

- type: playTimeTracker
  id: JobMarshal

- type: entity
  id: SpawnPointMarshal
  parent: SpawnPointHeadOfSecurity
  name: marshal
  components:
  - type: SpawnPoint
    job_id: Marshal

- type: roleLoadout
  id: JobMarshal
  groups:
  - MarshalHead
  - MarshalNeck
  - MarshalJumpsuit
  - KnightGloves
  - MarshalBackpack
  - MarshalOuterClothing
  - KnightShoes
  - KnightFace
  - KnightGlasses
  - KnightBelt
  - KnightEars
  - GeneralEncryptionKey
  - NfsdBoxSurvival
  - MarshalPDA
  - GeneralWallet
  - GeneralCartridge
  - GeneralImplanter
  - GeneralUtility
  - GeneralFun
  - GeneralTrinkets
  - GeneralBureaucracy
  - NFSpeciesSpecific
  - KnightPrimary
  - KnightSecondary
  - KnightAmmo
