- type: job
  id: Marshal
  name: job-name-marshal
  description: job-description-marshal
  playTimeTracker: JobMarshal
  requirements:
    - !type:DepartmentTimeRequirement
      department: Knights
      time: 43200 # 12 hours
  whitelisted: true
  startingGear: MarshalGear
  alwaysUseSpawner: true
  icon: "JobIconHeadOfSecurity"
  requireAdminNotify: true
  supervisors: job-supervisors-shipbaron
  weight: 180
  displayWeight: 70
  canBeAntag: false
  guides: [ BasicLore ]
  accessGroups:
  - MarshalAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: accessGroup
  id: MarshalAccess
  tags:
  - Maintenance
  - External
  - Command
  - Brig
  - Security
  - Armory
  - Mercenary
  - HeadOfSecurity

- type: startingGear
  id: MarshalGear
  equipment:
    pocket1: WeaponEnergyGunMultiphase # DeltaV gun
    pocket2: EnergySwordNfsd
    ears: ClothingHeadsetSecurity
  storage:
    back:
    - Multitool
    - DoorRemoteNfsd

- type: playTimeTracker
  id: JobMarshal

- type: entity
  id: SpawnPointMarshal
  parent: SpawnPointHeadOfSecurity
  name: marshal
  components:
  - type: SpawnPoint
    job_id: Marshal

- type: roleLoadout
  id: JobMarshal
  groups:
  - MarshalHead
  - MarshalNeck
  - MarshalJumpsuit
  - KnightGloves
  - MarshalBackpack
  - MarshalOuterClothing
  - KnightShoes
  - KnightFace
  - KnightGlasses
  - KnightBelt
#  - KnightEars # Commented this out because it's filled by the StartingGear component.
  - GeneralEncryptionKey
  - NfsdBoxSurvival
  - MarshalPDA
  - GeneralWallet
  - GeneralCartridge
  - GeneralImplanter
  - GeneralUtility
  - GeneralFun
  - GeneralTrinkets
  - GeneralBureaucracy
  - NFSpeciesSpecific
  - KnightPrimary
  - KnightSecondary
  - KnightAmmo

- type: entity
  parent: HoPIDCard
  id: MarshalIDCard
  name: Marshal ID card
  components:
  - type: PresetIdCard
    job: Marshal

- type: entity
  parent: BaseSecurityPDA
  id: MarshalPDA
  name: Marshal PDA
  description: Looks like it's been clawed on.
  components:
  - type: Pda
    id: MarshalIDCard
    penSlot:
      startingItem: PenCentcom
      priority: -1
      whitelist:
        tags:
        - Write
  - type: Appearance
    appearanceDataInit:
      enum.PdaVisuals.PdaType:
        !type:String
        pda-hop
  - type: PdaBorderColor
    borderColor: "#789876"
    accentHColor: "#447987"
  - type: Icon
    state: pda-hop
  - type: CartridgeLoader
    preinstalled:
    - CrewManifestCartridge
    - NotekeeperCartridge
    - NewsReaderCartridge
    - BountyContractsCartridge
    - AstroNavCartridge
    - LedgerCartridge
    - MailMetricsCartridge
