- type: job
  id: Squire
  name: job-name-squire
  description: job-description-squire
  playTimeTracker: JobSquire
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1 hr
  startingGear: SquireGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-marshal
  weight: 140
  displayWeight: 50
  canBeAntag: false
  guides: [ BasicLore ]
  accessGroups:
  - SquireAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddLanguageSpecial
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: SquireGear
  storage:
    back:
    - RadioHandheldNF # Mono

- type: playTimeTracker
  id: JobSquire

- type: entity
  id: SpawnPointSquire
  parent: SpawnPointSecurityCadet
  name: squire
  components:
  - type: SpawnPoint
    job_id: Squire

- type: accessGroup
  id: SquireAccess
  tags:
  - Maintenance
  - External
  - Command
  - Brig
  - Security
  - Mercenary

- type: roleLoadout
  id: JobSquire
  groups:
  - KnightHead
  - GeneralNeck
  - KnightJumpsuit
  - KnightGloves
  - KnightBackpack
  - KnightOuterClothing
  - KnightShoes
  - KnightFace
  - KnightGlasses
  - KnightBelt
  - KnightEars
  - GeneralEncryptionKey
  - NfsdBoxSurvival
  - KnightPDA
  - GeneralWallet
  - GeneralCartridge
  - GeneralImplanter
  - GeneralUtility
  - GeneralFun
  - GeneralTrinkets
  - GeneralBureaucracy
  - NFSpeciesSpecific
  - KnightPrimary
  - KnightSecondary
  - KnightAmmo
