using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.SafetyDepositBox.BUI;
using Content.Shared._WF.SafetyDepositBox.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._WF.SafetyDepositBox;

[GenerateTypedNameReferences]
public sealed partial class SafetyDepositConsoleWindow : FancyWindow
{
    public event Action<SafetyDepositBoxSize>? OnPurchasePressed;
    public event Action? OnDepositPressed;
    public event Action<Guid>? OnWithdrawPressed;

    public SafetyDepositConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        PurchaseSmallButton.OnPressed += _ => OnPurchasePressed?.Invoke(SafetyDepositBoxSize.Small);
        PurchaseMediumButton.OnPressed += _ => OnPurchasePressed?.Invoke(SafetyDepositBoxSize.Medium);
        PurchaseLargeButton.OnPressed += _ => OnPurchasePressed?.Invoke(SafetyDepositBoxSize.Large);
        DepositButton.OnPressed += _ => OnDepositPressed?.Invoke();
    }

    public void UpdateState(SafetyDepositConsoleState state)
    {
        // Update purchase buttons with costs
        PurchaseSmallButton.Disabled = false; // Bank account check happens server-side
        PurchaseSmallButton.Text = Loc.GetString("safety-deposit-console-purchase-small", ("cost", state.SmallBoxCost));
        
        PurchaseMediumButton.Disabled = false;
        PurchaseMediumButton.Text = Loc.GetString("safety-deposit-console-purchase-medium", ("cost", state.MediumBoxCost));
        
        PurchaseLargeButton.Disabled = false;
        PurchaseLargeButton.Text = Loc.GetString("safety-deposit-console-purchase-large", ("cost", state.LargeBoxCost));

        // Update deposit button
        DepositButton.Disabled = !state.HasBoxInSlot || state.BoxInSlot == null;

        // Update box slot status
        if (state.HasBoxInSlot && state.BoxInSlot != null)
        {
            BoxSlotLabel.Text = Loc.GetString("safety-deposit-console-box-in-slot",
                ("id", state.BoxInSlot.BoxId.ToString()[..8]));
        }
        else
        {
            BoxSlotLabel.Text = Loc.GetString("safety-deposit-console-no-box-in-slot");
        }

        // Update owned boxes list
        OwnedBoxesContainer.RemoveAllChildren();

        if (state.OwnedBoxes.Count == 0)
        {
            var noBoxesLabel = new Label
            {
                Text = Loc.GetString("safety-deposit-console-no-boxes"),
                StyleClasses = { "LabelSecondaryColor" },
                HorizontalAlignment = Control.HAlignment.Center,
                Margin = new Thickness(0, 20)
            };
            OwnedBoxesContainer.AddChild(noBoxesLabel);
        }
        else
        {
            // Sort boxes newest first (by BoxId descending)
            var sortedBoxes = state.OwnedBoxes.OrderByDescending(b => b.BoxId).ToList();
            
            var index = 0;
            foreach (var box in sortedBoxes)
            {
                // Create a clean row similar to shipyard
                var rowPanel = new PanelContainer
                {
                    HorizontalExpand = true,
                    StyleClasses = { "AngleRect" },
                    // Alternate row colors for better readability
                    ModulateSelfOverride = index % 2 == 0 ? new Color(0.15f, 0.15f, 0.15f) : new Color(0.12f, 0.12f, 0.12f)
                };

                var rowContainer = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    Margin = new Thickness(8, 4)
                };

                // Box info label - shows nickname if available, otherwise box ID and size
                var boxInfoText = !string.IsNullOrEmpty(box.Nickname)
                    ? $"{box.Nickname} ({box.BoxSize})"
                    : $"Box {box.BoxId.ToString()[..8]}... ({box.BoxSize})";

                var boxIdLabel = new Label
                {
                    Text = boxInfoText,
                    HorizontalExpand = true,
                    VerticalAlignment = Control.VAlignment.Center
                };

                // Status Label - fixed width, right aligned
                var statusLabel = new Label
                {
                    Text = box.IsDeposited
                        ? Loc.GetString("safety-deposit-console-box-deposited")
                        : Loc.GetString("safety-deposit-console-box-not-deposited"),
                    MinWidth = 80,
                    Align = Label.AlignMode.Right,
                    Margin = new Thickness(0, 0, 5, 0),
                    HorizontalAlignment = Control.HAlignment.Right,
                    VerticalAlignment = Control.VAlignment.Center,
                    FontColorOverride = box.IsDeposited ? Color.LightGreen : Color.Orange
                };

                // Withdraw button - fixed width
                var withdrawButton = new Button
                {
                    Text = Loc.GetString("safety-deposit-console-withdraw-button"),
                    Disabled = !box.IsDeposited,
                    MinWidth = 100,
                    HorizontalAlignment = Control.HAlignment.Right,
                    VerticalAlignment = Control.VAlignment.Center
                };

                var boxId = box.BoxId;
                withdrawButton.OnPressed += _ => OnWithdrawPressed?.Invoke(boxId);

                rowContainer.AddChild(boxIdLabel);
                rowContainer.AddChild(statusLabel);
                rowContainer.AddChild(withdrawButton);
                rowPanel.AddChild(rowContainer);
                OwnedBoxesContainer.AddChild(rowPanel);
                
                index++;
            }
        }
    }
}
